Use relative paths

diff --git a/bin/kdev b/bin/kdev
--- a/bin/kdev
+++ b/bin/kdev
@@ -1,15 +1,21 @@
 #!/usr/bin/env bash
 
+SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
+ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
+PROFILES_DIR="${SCRIPT_DIR}/../profiles"
+
 set -euo pipefail
 
 USER=$(whoami)
 
 set +u
 PROFILE="${1}"
+PROFILE_DIR="${PROFILES_DIR}/${PROFILE}"
 set -u
 
 KDEV_NAME="kdev-${USER}-${PROFILE}"
 KDEV_NAMESPACE="${KDEV_NAME}"
+MANIFEST_DIR="${ROOT_DIR}/tmp/${KDEV_NAME}"
 
 function main() {
 	if [[ $# -ne 2 ]]; then
@@ -89,22 +95,22 @@ function pod_fast_connect_if_exists() {
 }
 
 function pre_hook() {
-	if test -f "./profiles/${PROFILE}/pre-hook.sh"; then
+	if test -f "${PROFILE_DIR}/pre-hook.sh"; then
 		echo "==> running pre-hook"
-		./profiles/"${PROFILE}"/pre.sh
+		"${PROFILE_DIR}"/pre-hook.sh
 	fi
 }
 
 function profile_check() {
-	if ! test -d "./profiles/${PROFILE}"; then
-		echo "Error: profile not found: ./profiles/${PROFILE}"
+	if ! test -d "${PROFILE_DIR}"; then
+		echo "Error: profile not found: ${PROFILE_DIR}"
 		exit 1
 	fi
 }
 
 function profile_read() {
 	echo "==> reading profile config"
-	source "./profiles/${PROFILE}/config.sh"
+	source "${PROFILE_DIR}/config.sh"
 }
 
 function bucket_create() {
@@ -123,12 +129,12 @@ function bucket_create() {
 	fi
 
 	if [[ -z "${KDEV_BUCKET_LOCATION}" ]]; then
-		echo "Error: KDEV_BUCKET_LOCATION not set in profile config: ./profiles/${PROFILE}/config.sh"
+		echo "Error: KDEV_BUCKET_LOCATION not set in profile config: ${PROFILE_DIR}/config.sh"
 		exit 1
 	fi
 
 	if [[ -z "${KDEV_BUCKET_PROJECT}" ]]; then
-		echo "Error: KDEV_BUCKET_PROJECT not set in profile config: ./profiles/${PROFILE}/config.sh"
+		echo "Error: KDEV_BUCKET_PROJECT not set in profile config: ${PROFILE_DIR}/config.sh"
 		exit 1
 	fi
 	set -u
@@ -233,20 +239,20 @@ function bucket_destroy() {
 function manifests_template() {
 	echo
 	echo "==> templating manifests"
-	mkdir -p "./tmp/${KDEV_NAME}"
+	mkdir -p "${MANIFEST_DIR}"
 
-	for manifest in ./profiles/"${PROFILE}"/manifests/*.yaml; do
+	for manifest in "${PROFILE_DIR}"/manifests/*.yaml; do
 		echo
 		echo "templating: ${manifest}"
 		FILENAME=$(basename "${manifest}")
-		sed "s/KDEV_NAMESPACE/${KDEV_NAMESPACE}/g;s/KDEV_NAME/${KDEV_NAME}/g" "${manifest}" >"./tmp/${KDEV_NAME}/${FILENAME}"
+		sed "s/KDEV_NAMESPACE/${KDEV_NAMESPACE}/g;s/KDEV_NAME/${KDEV_NAME}/g" "${manifest}" >"${MANIFEST_DIR}/${FILENAME}"
 	done
 }
 
 function manifests_apply() {
 	echo
 	echo "==> applying manifests"
-	for manifest in "./tmp/${KDEV_NAME}"/*.yaml; do
+	for manifest in "${MANIFEST_DIR}"/*.yaml; do
 		if [[ $(basename "${manifest}") = "*_pod.yaml" ]]; then
 			continue
 		fi
@@ -260,17 +266,17 @@ function manifests_destroy() {
 	echo
 	echo "==> destroying manifests"
 
-	mkdir -p "./tmp/${KDEV_NAME}"
+	mkdir -p "${MANIFEST_DIR}"
 
-	for manifest in ./profiles/"${PROFILE}"/manifests/*.yaml; do
+	for manifest in "${PROFILE_DIR}"/manifests/*.yaml; do
 		echo
 		echo "templating: ${manifest}"
 		FILENAME=$(basename "${manifest}")
-		sed "s/KDEV_NAMESPACE/${KDEV_NAMESPACE}/g;s/KDEV_NAME/${KDEV_NAME}/g" "${manifest}" >"./tmp/${KDEV_NAME}/${FILENAME}"
+		sed "s/KDEV_NAMESPACE/${KDEV_NAMESPACE}/g;s/KDEV_NAME/${KDEV_NAME}/g" "${manifest}" >"${MANIFEST_DIR}/${FILENAME}"
 	done
 
 	# NOTE: reversed list
-	for manifest in $(ls -r ./tmp/"${KDEV_NAME}"/*.yaml); do
+	for manifest in $(ls -r "${MANIFEST_DIR}"/*.yaml); do
 		echo
 		echo "processing: ${manifest}"
 		set +e
@@ -294,12 +300,12 @@ function pod_init() {
 		echo "Error: pod not ready"
 		exit 1
 	else
-		if test -f "./profiles/${PROFILE}/init.sh"; then
+		if test -f "${PROFILE_DIR}/init.sh"; then
 			kubectl exec \
 				-i \
 				--namespace="${KDEV_NAME}" \
 				"${KDEV_NAME}" \
-				-- /bin/bash <./profiles/"${PROFILE}"/init.sh
+				-- /bin/bash <"${PROFILE_DIR}"/init.sh
 		fi
 	fi
 }
